version: 2

updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly

- package-ecosystem: "maven"
  directory: "/api"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10

- package-ecosystem: "docker"
  directory: "/ui"
  schedule:
    interval: weekly

- package-ecosystem: "docker"
  directory: "/api/src/main/docker"
  schedule:
    interval: weekly

- package-ecosystem: "npm"
  directory: "/ui"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
