---
version: '3.9'

services:
  console-api:
    image: ${CONSOLE_API_IMAGE}
    container_name: console-api
    network_mode: host
    volumes:
      - ${PWD}/console-config.yaml:/deployments/console-config.yaml:z
    environment:
      CONSOLE_CONFIG_PATH: /deployments/console-config.yaml
      QUARKUS_KUBERNETES_CLIENT_API_SERVER_URL: ${CONSOLE_API_KUBERNETES_API_SERVER_URL}
      QUARKUS_KUBERNETES_CLIENT_TRUST_CERTS: "true"
      QUARKUS_KUBERNETES_CLIENT_TOKEN: ${CONSOLE_API_SERVICE_ACCOUNT_TOKEN}

  console-ui:
    image: ${CONSOLE_UI_IMAGE}
    container_name: console-ui
    network_mode: host
    environment:
      HOSTNAME: localhost
      PORT: 3005
      NEXTAUTH_SECRET: ${CONSOLE_UI_NEXTAUTH_SECRET}
      NEXTAUTH_URL: http://localhost:3005
      BACKEND_URL: http://localhost:8080/
