kubernetes:
  # enable/disable use of Kubernetes to obtain additional information from Strimzi
  # Kafka and KafkaTopic custom resources. Enabled by default
  enabled: true

schemaRegistries:
  # Array of Apicurio Registries that my be referenced by Kafka cluster configurations
  # to resolve Avro or Protobuf schemas for topic message browsing
  - name: "my-apicurio-registry"
    url: "http://registry.exampl.com/apis/registry/v2/"

kafka:
  clusters:
    - name: my-kafka1 # name of the Strimzi Kafka CR
      namespace: my-namespace1 # namespace of the Strimzi Kafka CR (optional)
      id: my-kafka1-id # value to be used as an identifier for the cluster. Must be specified when namespace is not.
      listener: "secure" # name of the listener to use for connections from the console
      schemaRegistry: "my-apicurio-registry" # name of the schema registry to use with this Kafka (optional)
      # `properties` contains keys/values to use for any Kafka connection
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-512
        bootstrap.servers: my-kafka1.cloud.example.com:9093 # optional, if omitted the bootstrap servers from the Strimzi Kafka CR are used
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka1-user" password="sCr@m!";
      # `adminProperties` contains keys/values to use for Admin client Kafka connections.
      # Properties specified here override properties of the same name in `properties`
      adminProperties: {}
      # `consumerProperties` contains keys/values to use for Consumer client Kafka connections.
      # Properties specified here override properties of the same name in `properties`
      consumerProperties: {}
      # `producerProperties` contains keys/values to use for Producer client Kafka connections.
      # Properties specified here override properties of the same name in `properties`
      producerProperties: {}

    - name: my-kafka2
      namespace: my-namespace2
      listener: "secure"
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka2-user" password="sCr@m!";
