---
apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: example
spec:
  hostname: example-console.${CLUSTER_DOMAIN}

  metricsSources:
    # type=openshift-monitoring requires no other attributes, but truststore may be used if necessary
    - name: my-ocp-prometheus
      type: openshift-monitoring

  kafkaClusters:
    #
    # The values below make use of the example Kafka cluster from examples/kafka.
    # Adjust according to your environment.
    #
    - name: console-kafka             # Name of the `Kafka` CR representing the cluster
      namespace: ${KAFKA_NAMESPACE}   # Namespace of the `Kafka` CR representing the cluster
      listener: secure                # Listener on the `Kafka` CR to connect from the console
      metricsSource: my-ocp-prometheus # Name of the configured metrics source from the `metricsSources` section
      credentials:
        kafkaUser:
          name: console-kafka-user1   # Name of the `KafkaUser` resource used to connect to Kafka
                                      # This is optional if properties are used to configure the user
