---
kind: Secret
apiVersion: v1
metadata:
  name: console-dex
stringData:
  config.yaml: |
    issuer: https://console-dex.${CLUSTER_DOMAIN}

    storage:
      type: kubernetes
      config:
        inCluster: true

    web:
      http: 0.0.0.0:5556
      allowedOrigins: ['*']

    oauth2:
      skipApprovalScreen: true

    staticClients:
    - id: streamshub-console
      name: 'StreamsHub Console'
      secret: ${STATIC_CLIENT_SECRET}
      redirectURIs:
      - 'https://example-console.${CLUSTER_DOMAIN}/api/auth/callback/oidc'
      - 'http://localhost:3000/api/auth/callback/oidc'

    connectors:
    - type: openshift
      id: openshift
      name: OpenShift
      config:
        # OpenShift API, e.g. `https://api.example.com:6443`
        # Get from kubectl via `kubectl config view --minify=true --flatten=false -o json | jq -r .clusters[0].cluster.server`
        issuer: ${CLUSTER_APISERVER}

        # OpenShift root CA
        rootCA: /etc/ssl/openshift.pem

        # Communicate to OpenShift without validating SSL certificates
        insecureCA: false

        # Credentials can be string literals or pulled from the environment.
        clientID: ${${X}OPENSHIFT_OAUTH_CLIENT_ID}
        clientSecret: ${${X}OPENSHIFT_OAUTH_CLIENT_SECRET}

        # Optional list of required groups a user must be a member of
        groups: []

        # Redirect to the console's callback following authentication
        redirectURI: https://console-dex.${CLUSTER_DOMAIN}/callback

