apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels: {}
  template:
    metadata:
      labels: {}
    spec:
      containers:
        - name: prometheus
          image: quay.io/prometheus/prometheus:v2.55.1
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
            - name: prometheus-console-prometheus-db
              mountPath: /prometheus
          args:
            - '--storage.tsdb.retention.time=24h'
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
              - ALL
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-server-config
            defaultMode: 420
        - name: prometheus-console-prometheus-db
          emptyDir: {}
