name: Main changed - build, test, and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      node-version: 16.19.0

  test-and-deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3.0.2

      - uses: ./.github/actions/cache-restore
        id: cache-node-modules
        with:
          node-version: 16.19.0

      - name: Build storybook
        run: |
          export NEXTAUTH_SECRET=your_secret_value
          export NEXTAUTH_URL=""
          export KEYCLOAK_CLIENT_ID=""
          export KEYCLOAK_CLIENT_SECRET=""
          npm run build-storybook -- --quiet --loglevel silent

      - name: Deploy to Chromatic 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        id: chromatic
        with:
          branch: gh-pages # The branch the action should deploy to.
        env:
          NEXTAUTH_SECRET: FDezLOOo4q+DeG3y0REbc8xOlFvciDD4pRIvCRaBQ1k=
          NEXTAUTH_URL: http://localhost:3000
          KEYCLOAK_CLIENT_ID:
          KEYCLOAK_CLIENT_SECRET:
