name: Playwright Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v2

    - name: Install dependencies
      run: npm ci
      working-directory: ./ui
     
    - name: Run Playwright Tests
      run: |
        npm run build
        npm test
      working-directory: ./ui
