name: Playwright Tests

on:
  push:
    branches: [ 'main' ]
  pull_request_target:
    branches: [ 'main' ]
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v2

    - name: Install dependencies
      run: npm ci
      working-directory: ./ui
     
    - name: Run Playwright Tests
      env:
        BACKEND_URL: ${{ secrets.BACKEND_URL }}
        CONSOLE_METRICS_PROMETHEUS_URL: ${{ secrets.CONSOLE_METRICS_PROMETHEUS_URL }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
        CONSOLE_MODE: ${{ secrets.CONSOLE_MODE }}
      run: |
        npm run build
        npm test
      working-directory: ./ui
