name: Playwright Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v2

    - name: Install dependencies
      run: npm install

    - name: Deploy API
      run: |
        # Add commands to deploy your API to the specified environment
        echo "Deploying API to staging environment"
        # Your deployment commands go here

    - name: Run Playwright Tests
      run: |
        # Set the base URL for Playwright tests using an environment variable if needed
        #export BASE_URL=env.BASE_API_URL
        # Run npm test to execute your Playwright tests
        npm test
