name: Playwright Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v2

    - name: Install dependencies
      run: npm install
      working-directory: ./ui
     
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ./ui

    - name: Run Playwright Tests
      run:  npm run build && npm test
      working-directory: ./ui
