name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3.0.2

      - name: Build and Deploy
        uses: ./.github/workflows/reusable-build.yml
        with:
          node-version: 16.19.0
