name: Pre-Release

on:
  pull_request:
    paths:
      - '.github/project.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    name: pre release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Retrieve Project Metadata
        uses: radcortez/project-metadata-action@95ed3b828c4563fb1c1c9f4c319eceb9ce7de1b3
        id: metadata
        with:
          metadata-file-path: '.github/project.yml'

      - name: Review Milestone
        uses: radcortez/milestone-review-action@d75da69716e15f9ea52c5b77eb8bf3cfdd8299ad
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          milestone-title: ${{steps.metadata.outputs.current-version}}
