# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version to use"
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache-restore
        id: cache-node-modules
        with:
          node-version: ${{ inputs.node-version }}

  #  test-storybook:
  #    needs: setup
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v3
  #      - uses: ./.github/actions/cache-restore
  #        id: cache-node-modules
  #        with:
  #          node-version: ${{ inputs.node-version }}
  #      - name: Run the test suite
  #        run: npm run test-storybook:ci

  chromatic:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/cache-restore
        id: cache-node-modules
        with:
          node-version: 16.19.0

        #👇 Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        id: chromatic
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/ to obtain it
          projectToken: chpt_3bf820ceff3a2cb
          token: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true

   # Use the secrets in the tests
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID }}
          KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
