name: Build, Test, and Deploy

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version to use"
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache-restore
        id: cache-node-modules
        with:
          node-version: ${{ inputs.node-version }}

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/cache-restore
        id: cache-node-modules
        with:
          node-version: 16.19.0

      - name: Build storybook and Deploy to Chromatic 🚀
        uses: chromaui/action@v1
        id: chromatic
        with:
          projectToken: chpt_3bf820ceff3a2cb
          token: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true

        env:
          NEXTAUTH_SECRET: FDezLOOo4q+DeG3y0REbc8xOlFvciDD4pRIvCRaBQ1k=
          NEXTAUTH_URL: http://localhost:3000
          KEYCLOAK_CLIENT_ID: 
          KEYCLOAK_CLIENT_SECRET:
