---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consolereconciler-additional-cluster-role
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      # The cluster operator needs to access and manage leases for leader election
      # The "create" verb cannot be used with "resourceNames"
      - leases
    verbs:
      - create

  - apiGroups:
      - coordination.k8s.io
    resources:
      # The cluster operator needs to access and manage leases for leader election
      - leases
    resourceNames:
      - streamshub-console-operator-lease
    verbs:
      - get
      - list
      - watch
      - delete
      - patch
      - update
      # temporary until available: https://github.com/operator-framework/java-operator-sdk/pull/2456
      - create

  # Used by operator to discover the OpenShift Monitoring query endpoint
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    resourceNames:
      - thanos-querier
    verbs:
      - get

  # Granted to Prometheus instances
  - apiGroups: [ '' ]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: [ get, list, watch ]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs: [ get, list, watch ]
  - nonResourceURLs: [ /metrics ]
    verbs: [ get ]

  # Used directly by operator and granted to Console instances
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
      - kafkatopics
      - kafkausers

  # Granted to Console instances
  - verbs:
      - get
      - list
      - patch
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkarebalances
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consolereconciler-additional-cluster-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: consolereconciler-additional-cluster-role
subjects:
  - kind: ServiceAccount
    name: streamshub-console-operator
---
# Required in order to grant to console instances with OpenShift Cluster Monitoring integration
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: consolereconciler-cluster-monitoring-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: streamshub-console-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: console-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: console-operator
    spec:
      containers:
        - name: console-operator
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
            capabilities:
              drop:
              - ALL
